name: Node.js Package

on:
  workflow_dispatch:  # Trigger manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  # Removed the 'publish-gpr' job since you're not publishing to npm
